name: Kanpur Cloud Build
on: [push, workflow_dispatch] # workflow_dispatch se hum manually bhi button daba ke build kar sakte hain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix gradlew permissions
        run: chmod +x gradlew

      - name: Build with Stacktrace
        run: ./gradlew assembleDebug -x test -x lint -x configureNdkBuildDebug -x buildNdkBuildDebug --stacktrace
